#!/bin/bash

## source: https://github.com/gacallea/itn1_cluster
## I noticed that keeping some kind of control on the cache, helps the node.
## place this script in /root/itn1_helpers/itn1_synccache
## run this in a root crontab (crontab -e)
## */3 * * * * /root/itn1_helpers/itn1_synccache

howMuchCache=$(/usr/bin/free -m -w | /usr/bin/awk '/Mem:/ {print $7}')
maxCacheLimit=4000

if [ "$howMuchCache" -ge "$maxCacheLimit" ]; then
    echo -e "\\nCACHE DUMP OF ==> $howMuchCache <== AND SYNC @ $(date --iso-8601=ns)"
    /usr/bin/sync
    /usr/bin/echo 1 >/proc/sys/vm/drop_caches
else
    echo -e "\\nCACHE ==> $howMuchCache <== IS FINE @ $(date --iso-8601=ns)\\n"
fi
